[tool.poetry]
name = "technical-specification"
version = "0.1.0"
description = ""
authors = ["polinakigim <polinakigim@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.2.4"
djangorestframework = "^3.16.0"
python-dotenv = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
